version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  tracker:
    image: immortalis-backend-tracker 
    depends_on:
      - db
    build:
      context: .
      dockerfile: immortalis-backend-tracker/Dockerfile
    env_file:
      - ".env"

  api:
    image: immortalis-backend-api 
    depends_on:
      - db
    build:
      context: .
      dockerfile: immortalis-backend-api/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ".env"
  
  archiver:
    image: immortalis-backend-archiver 
    depends_on:
      - db
    build:
      context: .
      dockerfile: immortalis-backend-archiver/Dockerfile
    env_file:
      - ".env"

volumes:
  db:
    driver: local

  