pub const DATABASE_URL: &str = "DATABASE_URL";
pub const FILE_STORAGE_LOCATION: &str = "FILE_STORAGE_LOCATION";
pub const SKIP_DOWNLOAD: &str = "SKIP_DOWNLOAD";
pub const ARCHIVER_THREAD_COUNT: &str = "ARCHIVER_THREAD_COUNT";
pub const TRACKER_THREAD_COUNT: &str = "TRACKER_THREAD_COUNT";
pub const USE_IPV6: &str = "USE_IPV6";
