apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "immortalis.fullnameapi" . }}
  labels:
    {{- include "immortalis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "immortalis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "immortalis.apiSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "immortalis.fullnameapi" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@immortalis-postgresql/{{ .Values.postgresql.auth.database }}"  # replace localhost with db if running in container
            - name: FILE_STORAGE_LOCATION
              value: "/downloads/"
            - name: TEMP_FILE_STORAGE_LOCATION
              value: "/temp-downloads/"
            - name: SIMULATE_DOWNLOAD
              value: "false"
            - name: SIMULATED_DOWNLOAD_DURATION_SECONDS
              value: "0"
            - name: ARCHIVER_THREAD_COUNT
              value: "1"
            - name: ARCHIVER_ARCHIVING_TIMEOUT_SECONDS
              value: "6000"
            - name: ARCHIVER_ERROR_BACKOFF_SECONDS
              value: "600"
            - name: TRACKER_THREAD_COUNT
              value: "1"
            - name: USE_IPV6
              value: "false"

            - name: USE_S3
              value: "true"
            - name: S3_URL
              value: "https://{{ first .Values.minio.ingress.hosts}}"
            - name: S3_BUCKET_NAME
              value: {{ (first .Values.minio.buckets).name }}
              {{ with (first .Values.minio.users) }}
            - name: S3_ACCESS_KEY
              value: {{ .accessKey }}
            - name: S3_SECRET_KEY
              value: {{ .secretKey }}
              {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
