apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "immortalis.fullnameapi" . }}
  labels:
    {{- include "immortalis.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
