apiVersion: v1
kind: Service
metadata:
  name: {{ include "immortalis.fullnameapi" . }}
  labels:
    {{- include "immortalis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "immortalis.apiSelectorLabels" . | nindent 4 }}
