apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "immortalis.fullnameclient" . }}-config
  labels: {{ include "immortalis.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events {
        worker_connections  1024;
    }

    http {
      include  ./mime.types;
        server {
          gzip_static always;
          gzip_proxied expired no-cache no-store private auth;
            location ^~ / {
                alias /usr/share/nginx/html/;
                if (!-e $request_filename) { rewrite ^ /index.html last; }
                if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
                  expires 1M;
                  add_header Cache-Control "public, no-transform";
                }
            }
        }
    }