apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "immortalis.fullnameclient" . }}-config
  labels: {{ include "immortalis.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events {
        worker_connections  1024;
    }

    http {
      include  ./mime.types;
        server {
            location ^~ / {
                alias /usr/share/nginx/html/;
                if (!-e $request_filename) { rewrite ^ /index.html last; }
            }
        }
    }