apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "immortalis.fullnamemigrator" . }}
  labels:
    {{- include "immortalis.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
    {{ if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{ end }}