name: Publish

on:
  push:
    tags: '*.*.*'
  

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: FranzDiebold/github-env-vars-action@v2
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        #push: true
        tags: ${{ secrets.REGISTRY_URL }}/immortalis/immortalis-client:${{ env.CI_REF_NAME }}
        context: "./immortalis-client"
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: FranzDiebold/github-env-vars-action@v2
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        #push: true
        tags: ${{ secrets.REGISTRY_URL }}/immortalis/immortalis-backend-api:${{ env.CI_REF_NAME }}
        context: "./immortalis-backend"
        target: immortalis-backend-api
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        #push: true
        tags: ${{ secrets.REGISTRY_URL }}/immortalis/immortalis-backend-archiver:${{ env.CI_REF_NAME }}
        context: "./immortalis-backend"
        target: immortalis-backend-archiver
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        #push: true
        tags: ${{ secrets.REGISTRY_URL }}/immortalis/immortalis-backend-tracker:${{ env.CI_REF_NAME }}
        context: "./immortalis-backend"
        target: immortalis-backend-tracker
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        #push: true
        tags: ${{ secrets.REGISTRY_URL }}/immortalis/immortalis-backend-common:${{ env.CI_REF_NAME }}
        context: "./immortalis-backend"
        target: immortalis-backend-common
